# Site settings
title: CWM
tag_text: CWM
description: ([Resume](http://cwmart.in/Resume.pdf)) | ([Github](http://github.com/ChristopherWMartin/))| ([Email](mailto:cmarti14@artic.edu))
url: "http://cwmart.in"
baseurl: ""

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
