# Site settings
title: CWM
tag_text: CWM (Chris Martin)
url: "http://cwmart.in"
baseurl: ""

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
