# Site settings
title: Chris W. Martin
url: "http://cwmart.in"
baseurl: ""

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
