# Site settings
title: CWMart
email: cmarti14@artic.edu
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://cwmart.in” # the base hostname & protocol for your site 
github_username:  christopherwmartin

# Build settings
markdown: kramdown
permalink: pretty
