paginate = 10
paginatedSections = [ "post" ]

baseurl = "https://textfile.io"
pluralizeListTitles = false
staticDir = ["static"]
languageCode = "en-us"
title = "Textfile"
theme = "takeonrules-hugo-theme"
# theme = "hugo-tufte"
# theme = "etch"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

builddrafts = true
canonifyurls = true

[markup]
  defaultMarkdownHandler = "goldmark"

  [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true

  [markup.goldmark.parser]
    attribute = true
    autoHeadingID = true

  [markup.goldmark.renderer]
    hardWraps = false
    unsafe = true
    xHTML = false

  [markup.highlight]
    codeFences = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = true
    style = "tango"
    tabWidth = 2

[params]
  dark = "off"
  highlight = true
  copyright = ""
  showPoweredBy = false
  iso8601_format = "2006-01-02T15:04:05Z07:00"
  AuthorName = "Chris Martin"
  AuthorEmail = "chrismartin@riseup.net"


[frontmatter]
lastmod = ["lastmod", ":fileModTime", ":default"]

[[menu.me_elsewhere]]
  identifier = "github"
  name = "github.com/chriswmartin"
  url = "https://github.com/chriswmartin"

# [[menu.topnav]]
#   identifier = "p"
#   name = "Archive"
#   title = "Posts"
#   url = "/post/"

[[menu.topnav]]
  identifier = "r"
  name = "RSS"
  title = "RSS feed"
  url = "/index.xml"

[[menu.nav]]
  name = "Home"
  pre = "<i class='fa fa-home fa-lg'></i> "
  weight = -110
  identifier = "home"
  url = "/"
[[menu.nav]]
  name = "Posts"
  pre = "<i class='fa fa-book fa-lg'></i> "
  weight = -100
  identifier = "posts"
  url = "/post"
[[menu.nav]]
  name = "Rss"
  pre = "<i class='fa fa-rss fa-lg'></i> "
  weight = -100
  identifier = "rss"
  url = "/index.xml"

[outputs]
  home = [ "HTML", "JSON", "RSS", "ATOM" ]
  page = [ "HTML" ]
  section = [ "HTML" ]
  taxonomies = [ "HTML", "XML" ]

[mediaTypes."application/atom"]
  suffixes = [ "atom" ]

[outputFormats.Atom]
  mediaType = "application/atom"
  baseName = "index"
  isPlainText = false


