on:
  push:
    branches:
      - master
  workflow_dispatch:
name: update
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: install dependencies
      run: |
        sudo apt-get install python3-setuptools
        pip3 install -r requirements.txt
    - name: run
      run: python3 make.py 
        #    - uses: mikeal/publish-to-github-action@master
        # env:
        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # BRANCH_NAME: 'main'
